### add folder

POST http://127.0.0.1:8000/folder
Content-Type: application/json

{
  "title": "Tech",
  "parent_id": 1
}

### search user

GET http://127.0.0.1:8000/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ3d3IiLCJlbWFpbCI6Imlzd2FuZ3dyQGdtYWlsLmNvbSIsInJvbGVzIjpbImFkbWluIl0sImV4cCI6MTY2ODE2NjA5M30.w5IWg9fWt2mJwtRESo8IgNQY7j4ZwgXs1zER9_UYXzA
Content-Type: application/json

### update folder

PUT http://127.0.0.1:8000/folder
Content-Type: application/json

{
  "id": 6,
  "title": "test_title"
}

### delete folder

DELETE http://127.0.0.1:8000/folder/2
Content-Type: application/json
