### add folder

POST http://127.0.0.1:8000/folder
Content-Type: application/json

{
  "title": "Tech",
  "parent_id": 1
}

### search user

GET http://127.0.0.1:8000/folder?parent_id=1
Content-Type: application/json

### update folder

PUT http://127.0.0.1:8000/folder
Content-Type: application/json

{
  "id": 6,
  "title": "test_title"
}

### delete folder

DELETE http://127.0.0.1:8000/folder/2
Content-Type: application/json
