### add tag

POST http://127.0.0.1:8000/tag
Content-Type: application/json

{
  "name": "test_tag"
}

### add content to tag

PUT http://127.0.0.1:8000/tag
Content-Type: application/json

{
  "tag_id": "2",
  "add_content_ids": [35]
}

### remove content from tag

PUT http://127.0.0.1:8000/tag
Content-Type: application/json

{
  "tag_id": "2",
  "remove_content_ids": [35]
}



### delete tag

DELETE http://127.0.0.1:8000/tag/2
