### password login

POST http://127.0.0.1:8000/user/auth
Content-Type: application/json

{
  "username": "wwr",
  "password": "d49f8881148139a77be5d7d5b6561c58"
}

### add user

POST http://127.0.0.1:8000/user
Content-Type: application/json

{
  "username": "wwr3",
  "password": "d49f8881148139a77be5d7d5b6561c58",
  "email": "wang.wei.ran@outlook.com2"
}

### search user

GET http://127.0.0.1:8000/user/1
Content-Type: application/json

### update user

POST http://127.0.0.1:8000/user/update
Content-Type: application/json

{
  "id":37,
  "username": "wwr3",
  "password": "d49f8881148139a77be5d7d5b6561c58",
  "email": "test@email.com"
}

### delete user

