### add content

POST http://127.0.0.1:8000/content
Content-Type: application/json

{
  "title": "Test article",
  "parent_id": 1,
  "sub_title": "test sub title",
  "status": "draft",
  "content": "test_content"
}

### search contents

GET http://127.0.0.1:8000/content?parent_id=1
Content-Type: application/json

### update content

PUT http://127.0.0.1:8000/content
Content-Type: application/json

{
  "id": 2,
  "title": "test_title",
  "sub_title": "after update"
}

### delete folder

DELETE http://127.0.0.1:8000/folder/2
Content-Type: application/json
