"""add totp

Revision ID: 5f1533ae3bf3
Revises: 69366a21b194
Create Date: 2023-03-10 03:55:53.135831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f1533ae3bf3'
down_revision = '69366a21b194'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_user', sa.Column('two_fa_enforced', sa.Boolean(), nullable=True))
    op.execute('UPDATE sys_user SET two_fa_enforced = false')
    op.alter_column('sys_user', 'two_fa_enforced', nullable=False)
    op.add_column('sys_user', sa.Column('totp_key', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_user', 'totp_key')
    op.drop_column('sys_user', 'two_fa_enforced')
    # ### end Alembic commands ###
