"""empty message

Revision ID: bd5df1b0201c
Revises: 
Create Date: 2025-02-28 23:03:14.252101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd5df1b0201c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wwr_blog_post',
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('cover_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('preview', sa.TEXT(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wwr_blog_post_deleted'), 'wwr_blog_post', ['deleted'], unique=False)
    op.create_index(op.f('ix_wwr_blog_post_status'), 'wwr_blog_post', ['status'], unique=False)
    op.create_index(op.f('ix_wwr_blog_post_title'), 'wwr_blog_post', ['title'], unique=False)
    op.create_table('wwr_entity_relation',
    sa.Column('src_id', sa.Integer(), nullable=False),
    sa.Column('dst_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wwr_entity_relation_deleted'), 'wwr_entity_relation', ['deleted'], unique=False)
    op.create_index(op.f('ix_wwr_entity_relation_dst_id'), 'wwr_entity_relation', ['dst_id'], unique=False)
    op.create_index(op.f('ix_wwr_entity_relation_src_id'), 'wwr_entity_relation', ['src_id'], unique=False)
    op.create_table('wwr_post_resource',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('url', sa.TEXT(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wwr_post_resource_deleted'), 'wwr_post_resource', ['deleted'], unique=False)
    op.create_index(op.f('ix_wwr_post_resource_post_id'), 'wwr_post_resource', ['post_id'], unique=False)
    op.create_table('wwr_post_tag',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'type', name='uix_name_type')
    )
    op.create_index(op.f('ix_wwr_post_tag_deleted'), 'wwr_post_tag', ['deleted'], unique=False)
    op.create_table('wwr_sys_config',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_wwr_sys_config_deleted'), 'wwr_sys_config', ['deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wwr_sys_config_deleted'), table_name='wwr_sys_config')
    op.drop_table('wwr_sys_config')
    op.drop_index(op.f('ix_wwr_post_tag_deleted'), table_name='wwr_post_tag')
    op.drop_table('wwr_post_tag')
    op.drop_index(op.f('ix_wwr_post_resource_post_id'), table_name='wwr_post_resource')
    op.drop_index(op.f('ix_wwr_post_resource_deleted'), table_name='wwr_post_resource')
    op.drop_table('wwr_post_resource')
    op.drop_index(op.f('ix_wwr_entity_relation_src_id'), table_name='wwr_entity_relation')
    op.drop_index(op.f('ix_wwr_entity_relation_dst_id'), table_name='wwr_entity_relation')
    op.drop_index(op.f('ix_wwr_entity_relation_deleted'), table_name='wwr_entity_relation')
    op.drop_table('wwr_entity_relation')
    op.drop_index(op.f('ix_wwr_blog_post_title'), table_name='wwr_blog_post')
    op.drop_index(op.f('ix_wwr_blog_post_status'), table_name='wwr_blog_post')
    op.drop_index(op.f('ix_wwr_blog_post_deleted'), table_name='wwr_blog_post')
    op.drop_table('wwr_blog_post')
    # ### end Alembic commands ###
