"""init

Revision ID: e97d27b3a8d3
Revises: 
Create Date: 2023-03-03 15:32:47.496845

"""
# revision identifiers, used by Alembic.
revision = 'e97d27b3a8d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
