"""change_sys_user

Revision ID: ee011f74a986
Revises: e97d27b3a8d3
Create Date: 2023-03-03 15:36:28.119821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee011f74a986'
down_revision = 'e97d27b3a8d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_user', 'salt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_user', sa.Column('salt', sa.VARCHAR(length=128), autoincrement=False, nullable=True, comment='salt'))
    # ### end Alembic commands ###
