name: Dockerhub Release
on:
  push:
    branches:
      - 'release'
    paths:
      - 'version.txt'
  workflow_dispatch:
jobs:
  dockerhub:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - run: echo version=$(cat version.txt) >> $GITHUB_ENV
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: wwricu
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          sbom: true
          provenance: mode=max
          tags: wwricu/basic-service:${{ env.version }}, wwricu/basic-service:latest
