name: Pypi Release
on:
  push:
    branches:
      - 'release'
    paths:
      - 'version.txt'
  workflow_dispatch:
jobs:
  pypi:
    runs-on: ubuntu-latest
    permissions: write-all
    continue-on-error: true
    environment:
      name: pypi
      url: https://pypi.org/project/wwricu
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          python -m pip install build
          python -m build
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
